// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var gameSettings = GameSettings.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GameSettings
    {
        [JsonProperty("FloatingText")]
        public Dictionary<string, bool> FloatingText { get; set; }

        [JsonProperty("General")]
        public General General { get; set; }

        [JsonProperty("HUD")]
        public Hud Hud { get; set; }

        [JsonProperty("LossOfControl")]
        public LossOfControl LossOfControl { get; set; }

        [JsonProperty("Performance")]
        public Performance Performance { get; set; }

        [JsonProperty("Voice")]
        public Voice Voice { get; set; }

        [JsonProperty("Volume")]
        public Volume Volume { get; set; }
    }

    public partial class General
    {
        private bool autoAcquireTarget;

        public bool GetAutoAcquireTarget()
        {
            return autoAcquireTarget;
        }

        public void SetAutoAcquireTarget(bool value)
        {
            autoAcquireTarget = value;
        }

        private bool bindSysKeys;

        public bool GetBindSysKeys()
        {
            return bindSysKeys;
        }

        public void SetBindSysKeys(bool value)
        {
            bindSysKeys = value;
        }

        private bool cursorOverride;

        public bool GetCursorOverride()
        {
            return cursorOverride;
        }

        public void SetCursorOverride(bool value)
        {
            cursorOverride = value;
        }

        private double cursorScale;

        public double GetCursorScale()
        {
            return cursorScale;
        }

        public void SetCursorScale(double value)
        {
            cursorScale = value;
        }

        private bool enableAudio;

        public bool GetEnableAudio()
        {
            return enableAudio;
        }

        public void SetEnableAudio(bool value)
        {
            enableAudio = value;
        }

        private bool enableTargetedAttackMove;

        public bool GetEnableTargetedAttackMove()
        {
            return enableTargetedAttackMove;
        }

        public void SetEnableTargetedAttackMove(bool value)
        {
            enableTargetedAttackMove = value;
        }

        private long gameMouseSpeed;

        public long GetGameMouseSpeed()
        {
            return gameMouseSpeed;
        }

        public void SetGameMouseSpeed(long value)
        {
            gameMouseSpeed = value;
        }

        private bool hideEyeCandy;

        public bool GetHideEyeCandy()
        {
            return hideEyeCandy;
        }

        public void SetHideEyeCandy(bool value)
        {
            hideEyeCandy = value;
        }

        private bool osxMouseAcceleration;

        public bool GetOsxMouseAcceleration()
        {
            return osxMouseAcceleration;
        }

        public void SetOsxMouseAcceleration(bool value)
        {
            osxMouseAcceleration = value;
        }

        private bool predictMovement;

        public bool GetPredictMovement()
        {
            return predictMovement;
        }

        public void SetPredictMovement(bool value)
        {
            predictMovement = value;
        }

        private bool preferDx9LegacyMode;

        public bool GetPreferDx9LegacyMode()
        {
            return preferDx9LegacyMode;
        }

        public void SetPreferDx9LegacyMode(bool value)
        {
            preferDx9LegacyMode = value;
        }

        private bool preferOpenGlLegacyMode;

        public bool GetPreferOpenGlLegacyMode()
        {
            return preferOpenGlLegacyMode;
        }

        public void SetPreferOpenGlLegacyMode(bool value)
        {
            preferOpenGlLegacyMode = value;
        }

        private bool recommendJunglePaths;

        public bool GetRecommendJunglePaths()
        {
            return recommendJunglePaths;
        }

        public void SetRecommendJunglePaths(bool value)
        {
            recommendJunglePaths = value;
        }

        private bool relativeTeamColors;

        public bool GetRelativeTeamColors()
        {
            return relativeTeamColors;
        }

        public void SetRelativeTeamColors(bool value)
        {
            relativeTeamColors = value;
        }

        private bool showCursorLocator;

        public bool GetShowCursorLocator()
        {
            return showCursorLocator;
        }

        public void SetShowCursorLocator(bool value)
        {
            showCursorLocator = value;
        }

        private bool showGodray;

        public bool GetShowGodray()
        {
            return showGodray;
        }

        public void SetShowGodray(bool value)
        {
            showGodray = value;
        }

        private bool showTurretRangeIndicators;

        public bool GetShowTurretRangeIndicators()
        {
            return showTurretRangeIndicators;
        }

        public void SetShowTurretRangeIndicators(bool value)
        {
            showTurretRangeIndicators = value;
        }

        private bool snapCameraOnRespawn;

        public bool GetSnapCameraOnRespawn()
        {
            return snapCameraOnRespawn;
        }

        public void SetSnapCameraOnRespawn(bool value)
        {
            snapCameraOnRespawn = value;
        }

        private long themeMusic;

        public long GetThemeMusic()
        {
            return themeMusic;
        }

        public void SetThemeMusic(long value)
        {
            themeMusic = value;
        }

        private bool waitForVerticalSync;

        public bool GetWaitForVerticalSync()
        {
            return waitForVerticalSync;
        }

        public void SetWaitForVerticalSync(bool value)
        {
            waitForVerticalSync = value;
        }

        private long windowMode;

        public long GetWindowMode()
        {
            return windowMode;
        }

        public void SetWindowMode(long value)
        {
            windowMode = value;
        }
    }

    public partial class Hud
    {
        private bool autoDisplayTarget;

        public bool GetAutoDisplayTarget()
        {
            return autoDisplayTarget;
        }

        public void SetAutoDisplayTarget(bool value)
        {
            autoDisplayTarget = value;
        }

        private long cameraLockMode;

        public long GetCameraLockMode()
        {
            return cameraLockMode;
        }

        public void SetCameraLockMode(long value)
        {
            cameraLockMode = value;
        }

        private long chatChannelVisibility;

        public long GetChatChannelVisibility()
        {
            return chatChannelVisibility;
        }

        public void SetChatChannelVisibility(long value)
        {
            chatChannelVisibility = value;
        }

        private long chatScale;

        public long GetChatScale()
        {
            return chatScale;
        }

        public void SetChatScale(long value)
        {
            chatScale = value;
        }

        private bool disableHudSpellClick;

        public bool GetDisableHudSpellClick()
        {
            return disableHudSpellClick;
        }

        public void SetDisableHudSpellClick(bool value)
        {
            disableHudSpellClick = value;
        }

        private bool drawHealthBars;

        public bool GetDrawHealthBars()
        {
            return drawHealthBars;
        }

        public void SetDrawHealthBars(bool value)
        {
            drawHealthBars = value;
        }

        private long emotePopupUiDisplayMode;

        public long GetEmotePopupUiDisplayMode()
        {
            return emotePopupUiDisplayMode;
        }

        public void SetEmotePopupUiDisplayMode(long value)
        {
            emotePopupUiDisplayMode = value;
        }

        private long emoteSize;

        public long GetEmoteSize()
        {
            return emoteSize;
        }

        public void SetEmoteSize(long value)
        {
            emoteSize = value;
        }

        private bool enableLineMissileVis;

        public bool GetEnableLineMissileVis()
        {
            return enableLineMissileVis;
        }

        public void SetEnableLineMissileVis(bool value)
        {
            enableLineMissileVis = value;
        }

        private long eternalsMilestoneDisplayMode;

        public long GetEternalsMilestoneDisplayMode()
        {
            return eternalsMilestoneDisplayMode;
        }

        public void SetEternalsMilestoneDisplayMode(long value)
        {
            eternalsMilestoneDisplayMode = value;
        }

        private bool flashScreenWhenDamaged;

        public bool GetFlashScreenWhenDamaged()
        {
            return flashScreenWhenDamaged;
        }

        public void SetFlashScreenWhenDamaged(bool value)
        {
            flashScreenWhenDamaged = value;
        }

        private bool flashScreenWhenStunned;

        public bool GetFlashScreenWhenStunned()
        {
            return flashScreenWhenStunned;
        }

        public void SetFlashScreenWhenStunned(bool value)
        {
            flashScreenWhenStunned = value;
        }

        private bool flipMiniMap;

        public bool GetFlipMiniMap()
        {
            return flipMiniMap;
        }

        public void SetFlipMiniMap(bool value)
        {
            flipMiniMap = value;
        }

        private long globalScale;

        public long GetGlobalScale()
        {
            return globalScale;
        }

        public void SetGlobalScale(long value)
        {
            globalScale = value;
        }

        private long keyboardScrollSpeed;

        public long GetKeyboardScrollSpeed()
        {
            return keyboardScrollSpeed;
        }

        public void SetKeyboardScrollSpeed(long value)
        {
            keyboardScrollSpeed = value;
        }

        private double mapScrollSpeed;

        public double GetMapScrollSpeed()
        {
            return mapScrollSpeed;
        }

        public void SetMapScrollSpeed(double value)
        {
            mapScrollSpeed = value;
        }

        private bool middleClickDragScrollEnabled;

        public bool GetMiddleClickDragScrollEnabled()
        {
            return middleClickDragScrollEnabled;
        }

        public void SetMiddleClickDragScrollEnabled(bool value)
        {
            middleClickDragScrollEnabled = value;
        }

        private bool minimapMoveSelf;

        public bool GetMinimapMoveSelf()
        {
            return minimapMoveSelf;
        }

        public void SetMinimapMoveSelf(bool value)
        {
            minimapMoveSelf = value;
        }

        private double minimapScale;

        public double GetMinimapScale()
        {
            return minimapScale;
        }

        public void SetMinimapScale(double value)
        {
            minimapScale = value;
        }

        private bool mirroredScoreboard;

        public bool GetMirroredScoreboard()
        {
            return mirroredScoreboard;
        }

        public void SetMirroredScoreboard(bool value)
        {
            mirroredScoreboard = value;
        }

        private long numericCooldownFormat;

        public long GetNumericCooldownFormat()
        {
            return numericCooldownFormat;
        }

        public void SetNumericCooldownFormat(long value)
        {
            numericCooldownFormat = value;
        }

        private long objectiveVoteScale;

        public long GetObjectiveVoteScale()
        {
            return objectiveVoteScale;
        }

        public void SetObjectiveVoteScale(long value)
        {
            objectiveVoteScale = value;
        }

        private bool scrollSmoothingEnabled;

        public bool GetScrollSmoothingEnabled()
        {
            return scrollSmoothingEnabled;
        }

        public void SetScrollSmoothingEnabled(bool value)
        {
            scrollSmoothingEnabled = value;
        }

        private bool showAllChannelChat;

        public bool GetShowAllChannelChat()
        {
            return showAllChannelChat;
        }

        public void SetShowAllChannelChat(bool value)
        {
            showAllChannelChat = value;
        }

        private bool showAlliedChat;

        public bool GetShowAlliedChat()
        {
            return showAlliedChat;
        }

        public void SetShowAlliedChat(bool value)
        {
            showAlliedChat = value;
        }

        private bool showAttackRadius;

        public bool GetShowAttackRadius()
        {
            return showAttackRadius;
        }

        public void SetShowAttackRadius(bool value)
        {
            showAttackRadius = value;
        }

        private bool showNeutralCamps;

        public bool GetShowNeutralCamps()
        {
            return showNeutralCamps;
        }

        public void SetShowNeutralCamps(bool value)
        {
            showNeutralCamps = value;
        }

        private bool showOffScreenPointsOfInterest;

        public bool GetShowOffScreenPointsOfInterest()
        {
            return showOffScreenPointsOfInterest;
        }

        public void SetShowOffScreenPointsOfInterest(bool value)
        {
            showOffScreenPointsOfInterest = value;
        }

        private bool showSpellCosts;

        public bool GetShowSpellCosts()
        {
            return showSpellCosts;
        }

        public void SetShowSpellCosts(bool value)
        {
            showSpellCosts = value;
        }

        private bool showSpellRecommendations;

        public bool GetShowSpellRecommendations()
        {
            return showSpellRecommendations;
        }

        public void SetShowSpellRecommendations(bool value)
        {
            showSpellRecommendations = value;
        }

        private bool showSummonerNames;

        public bool GetShowSummonerNames()
        {
            return showSummonerNames;
        }

        public void SetShowSummonerNames(bool value)
        {
            showSummonerNames = value;
        }

        private bool showSummonerNamesInScoreboard;

        public bool GetShowSummonerNamesInScoreboard()
        {
            return showSummonerNamesInScoreboard;
        }

        public void SetShowSummonerNamesInScoreboard(bool value)
        {
            showSummonerNamesInScoreboard = value;
        }

        private bool showTeamFramesOnLeft;

        public bool GetShowTeamFramesOnLeft()
        {
            return showTeamFramesOnLeft;
        }

        public void SetShowTeamFramesOnLeft(bool value)
        {
            showTeamFramesOnLeft = value;
        }

        private bool showTimestamps;

        public bool GetShowTimestamps()
        {
            return showTimestamps;
        }

        public void SetShowTimestamps(bool value)
        {
            showTimestamps = value;
        }

        private bool smartCastOnKeyRelease;

        public bool GetSmartCastOnKeyRelease()
        {
            return smartCastOnKeyRelease;
        }

        public void SetSmartCastOnKeyRelease(bool value)
        {
            smartCastOnKeyRelease = value;
        }

        private bool smartCastWithIndicatorCastWhenNewSpellSelected;

        public bool GetSmartCastWithIndicatorCastWhenNewSpellSelected()
        {
            return smartCastWithIndicatorCastWhenNewSpellSelected;
        }

        public void SetSmartCastWithIndicatorCastWhenNewSpellSelected(bool value)
        {
            smartCastWithIndicatorCastWhenNewSpellSelected = value;
        }
    }

    public partial class LossOfControl
    {
        private bool lossOfControlEnabled;

        public bool GetLossOfControlEnabled()
        {
            return lossOfControlEnabled;
        }

        public void SetLossOfControlEnabled(bool value)
        {
            lossOfControlEnabled = value;
        }

        private bool showSlows;

        public bool GetShowSlows()
        {
            return showSlows;
        }

        public void SetShowSlows(bool value)
        {
            showSlows = value;
        }
    }

    public partial class Performance
    {
        private bool enableHudAnimations;

        public bool GetEnableHudAnimations()
        {
            return enableHudAnimations;
        }

        public void SetEnableHudAnimations(bool value)
        {
            enableHudAnimations = value;
        }
    }

    public partial class Voice
    {
        private bool showVoiceChatHalos;

        public bool GetShowVoiceChatHalos()
        {
            return showVoiceChatHalos;
        }

        public void SetShowVoiceChatHalos(bool value)
        {
            showVoiceChatHalos = value;
        }

        private bool showVoicePanelWithScoreboard;

        public bool GetShowVoicePanelWithScoreboard()
        {
            return showVoicePanelWithScoreboard;
        }

        public void SetShowVoicePanelWithScoreboard(bool value)
        {
            showVoicePanelWithScoreboard = value;
        }
    }

    public partial class Volume
    {
        private bool ambienceMute;

        public bool GetAmbienceMute()
        {
            return ambienceMute;
        }

        public void SetAmbienceMute(bool value)
        {
            ambienceMute = value;
        }

        private long ambienceVolume;

        public long GetAmbienceVolume()
        {
            return ambienceVolume;
        }

        public void SetAmbienceVolume(long value)
        {
            ambienceVolume = value;
        }

        private bool announcerMute;

        public bool GetAnnouncerMute()
        {
            return announcerMute;
        }

        public void SetAnnouncerMute(bool value)
        {
            announcerMute = value;
        }

        private long announcerVolume;

        public long GetAnnouncerVolume()
        {
            return announcerVolume;
        }

        public void SetAnnouncerVolume(long value)
        {
            announcerVolume = value;
        }

        private bool masterMute;

        public bool GetMasterMute()
        {
            return masterMute;
        }

        public void SetMasterMute(bool value)
        {
            masterMute = value;
        }

        private long masterVolume;

        public long GetMasterVolume()
        {
            return masterVolume;
        }

        public void SetMasterVolume(long value)
        {
            masterVolume = value;
        }

        private bool musicMute;

        public bool GetMusicMute()
        {
            return musicMute;
        }

        public void SetMusicMute(bool value)
        {
            musicMute = value;
        }

        private long musicVolume;

        public long GetMusicVolume()
        {
            return musicVolume;
        }

        public void SetMusicVolume(long value)
        {
            musicVolume = value;
        }

        private bool pingsMute;

        public bool GetPingsMute()
        {
            return pingsMute;
        }

        public void SetPingsMute(bool value)
        {
            pingsMute = value;
        }

        private long pingsVolume;

        public long GetPingsVolume()
        {
            return pingsVolume;
        }

        public void SetPingsVolume(long value)
        {
            pingsVolume = value;
        }

        private bool sfxMute;

        public bool GetSfxMute()
        {
            return sfxMute;
        }

        public void SetSfxMute(bool value)
        {
            sfxMute = value;
        }

        private long sfxVolume;

        public long GetSfxVolume()
        {
            return sfxVolume;
        }

        public void SetSfxVolume(long value)
        {
            sfxVolume = value;
        }

        private bool voiceMute;

        public bool GetVoiceMute()
        {
            return voiceMute;
        }

        public void SetVoiceMute(bool value)
        {
            voiceMute = value;
        }

        private long voiceVolume;

        public long GetVoiceVolume()
        {
            return voiceVolume;
        }

        public void SetVoiceVolume(long value)
        {
            voiceVolume = value;
        }
    }

    public partial class GameSettings
    {
        public static GameSettings FromJson(string json) => JsonConvert.DeserializeObject<GameSettings>(json, QuickType.Converter.Settings);
    }
}
