// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var gameVersion = GameVersion.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GameVersion
    {
        [JsonProperty("branch")]
        public string Branch { get; set; }

        [JsonProperty("patchline")]
        public string Patchline { get; set; }

        [JsonProperty("patchlineVisibleName")]
        public string PatchlineVisibleName { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }
    }

    public partial class GameVersion
    {
        public static GameVersion FromJson(string json) => JsonConvert.DeserializeObject<GameVersion>(json, QuickType.Converter.Settings);
    }
}
