// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var champSelectSession = ChampSelectSession.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LockChamp
    {
        [JsonProperty("championId")]
        public long ChampionId { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }
    }

    public partial class LockChamp
    {
        public static ChampSelectSession FromJson(string json) => JsonConvert.DeserializeObject<ChampSelectSession>(json, QuickType.Converter.Settings);
    }
}
