// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var profileSkin = ProfileSkin.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ProfileSkin
    {
        [JsonProperty("backgroundSkinId")]
        public long BackgroundSkinId { get; set; }

        [JsonProperty("regalia")]
        public string Regalia { get; set; }
    }

    public partial class ProfileSkin
    {
        public static ProfileSkin FromJson(string json) => JsonConvert.DeserializeObject<ProfileSkin>(json, QuickType.Converter.Settings);
    }
}
